import { notFound } from "next/navigation";
import "./print.css";

const assets = {
  "brand-guidelines": { eyebrow: "Brand system / independent concept", title: "The Precision Management brand system", deck: "A disciplined identity designed to make a multifamily operator's scale, care, and compliance expertise visible at every touchpoint." },
  "owner-acquisition": { eyebrow: "Owner acquisition / one-sheet", title: "Comprehensive management, from strategy to service.", deck: "A focused leave-behind for property owners evaluating a management partner." },
  "resident-communication": { eyebrow: "Resident communication / template", title: "Maintenance update", deck: "A practical template built for clarity, service expectations, and resident support." },
  "print-collateral": { eyebrow: "Print collateral / concept", title: "A system that holds up in the real world.", deck: "Business card and letterhead applications for owner, partner, and vendor communication." },
  "website-ui": { eyebrow: "Website/UI / concept", title: "Two clear paths. One credible operating story.", deck: "A homepage direction for owners evaluating expertise and residents seeking support." },
} as const;

type Asset = keyof typeof assets;
const logo = "/assets/exports/logo-system/precision-management-official-logo.svg";
const photo = "/assets/exports/source-images/hero-atlanta.jpg";

function Header({ label }: { label: string }) { return <header className="print-header"><img src={logo} alt="Precision Management"/><span>PRECISION MANAGEMENT</span><b>{label}</b></header>; }
function Footer() { return <footer className="print-footer">Independent concept by Ger&apos;Quia Abner. Not commissioned by, affiliated with, or endorsed by Precision Management.</footer>; }
function Metrics() { return <div className="metrics"><div><strong>80+</strong><span>Properties managed</span></div><div><strong>11,000+</strong><span>Units</span></div><div><strong>20+</strong><span>Years experience</span></div></div>; }
function EditableDocument({ children }: { children: React.ReactNode }) { return <main className="print-document" contentEditable suppressContentEditableWarning aria-label="Editable Precision Management template">{children}</main>; }
function Cover({ asset }: { asset: Asset }) { const item = assets[asset]; return <section className="pdf-page cover"><img className="cover-photo" src={photo} alt="Precision Management portfolio community"/><div className="cover-shade"/><div className="cover-content"><Header label={item.eyebrow}/><div className="cover-copy"><p className="kicker">Lead with Passion. Serve with Precision.</p><h1>{item.title}</h1><p>{item.deck}</p></div><Metrics/><Footer/></div></section>; }
function BrandGuidelines() { return <><section className="pdf-page"><Header label="Brand guidelines"/><div className="intro"><p className="kicker">System reference</p><h1>Identity with operational discipline.</h1><p>Precision Management&apos;s visual system should feel like the organization behind it: experienced, hands-on, accountable, and built to scale.</p></div><div className="brand-grid"><div className="logo-panel"><img src={logo} alt="Official Precision Management logo"/><p>Official logo supplied from precisionmngmt.com. Keep clear space equal to the mark&apos;s outer ring.</p></div><div><p className="kicker">Typography</p><h2>SF Pro Display</h2><p>Regular for reading. Medium for interface labels. Bold for the few messages that need authority.</p><div className="type-sample">Precision is visible.</div></div></div><Footer/></section><section className="pdf-page"><Header label="Brand guidelines / application"/><div className="intro"><p className="kicker">Color roles</p><h1>Use color to organize, not decorate.</h1></div><div className="swatches"><div><i className="navy"/><b>Precision Navy</b><span>#1C2C44</span></div><div><i className="teal"/><b>Managed Teal</b><span>#3D8C8F</span></div><div><i className="gold"/><b>Maintenance Gold</b><span>#D6B055</span></div><div><i className="paper"/><b>Paper White</b><span>#FFFFFF</span></div></div><div className="callout"><img src={photo} alt="Precision Management property"/><div><p className="kicker">Image direction</p><h2>Use real properties as proof.</h2><p>Property imagery should establish the environment. The message and next step remain legible, specific, and supported by the official mark.</p></div></div><Footer/></section></>; }
function OwnerSheet() { return <><section className="pdf-page"><Header label="Owner acquisition one-sheet"/><div className="owner-hero"><div><p className="kicker">Property management partner</p><h1>Comprehensive management, from strategy to service.</h1><p>Precision Management brings hands-on management, scalable systems, and a personalized approach to multifamily real estate.</p><Metrics/></div><img src={photo} alt="Precision Management portfolio community"/></div><div className="three-columns"><div><p className="kicker">Portfolio</p><h3>Built for multifamily.</h3><p>Conventional, student, and affordable housing across multiple states.</p></div><div><p className="kicker">Compliance</p><h3>Confidence in complexity.</h3><p>HUD 50059, LIHTC, and HOME program expertise.</p></div><div><p className="kicker">Start here</p><h3>Assess. Plan. Onboard.</h3><p>Begin with an assessment, receive a tailored proposal, then transition with dedicated support.</p></div></div><div className="owner-cta"><div><p className="kicker">Start a conversation</p><h2>Request a management assessment.</h2></div><div><b>precisionmngmt.com</b><span>contact@precisionmngmt.com · 1-732-627-1410</span></div></div><Footer/></section></>; }
function ResidentNotice() { return <section className="pdf-page resident"><Header label="Resident communication template"/><div className="notice-title"><p className="kicker">Property update</p><h1>Maintenance update</h1><p>Prepared for clear communication, resident support, and a responsive maintenance process.</p></div><div className="notice-box"><p><b>Subject:</b> [Service update / scheduled maintenance]</p><p>Dear Resident,</p><p>We are writing to share an update regarding <b>[service area or maintenance activity]</b>. Our team is working to keep you informed and to make the next step straightforward.</p><p><b>What to expect</b></p><ul><li>[Date and anticipated time window]</li><li>[Access, parking, or preparation instruction if applicable]</li><li>[How to request support or report an issue]</li></ul><p>If you have a question, please contact your property team through the designated resident channel. Thank you for your patience and cooperation.</p><p>Sincerely,<br/><b>Precision Management</b></p></div><div className="support-strip"><b>Resident support</b><span>Clear communication · Service expectations · Simple next steps</span></div><Footer/></section>; }
function PrintCollateral() { return <><section className="pdf-page"><Header label="Print collateral concept"/><div className="intro"><p className="kicker">Business card</p><h1>Small format. Full confidence.</h1></div><div className="business-card"><div><img src={logo} alt="Precision Management"/><p>PRECISION MANAGEMENT</p></div><div><p>Lead with Passion.<br/><b>Serve with Precision.</b></p><small>precisionmngmt.com</small></div></div><div className="print-notes"><div><b>Front</b><span>Official mark and restrained identification.</span></div><div><b>Back</b><span>One memorable line and a direct digital path.</span></div></div><Footer/></section><section className="pdf-page"><Header label="Print collateral / letterhead"/><div className="letterhead"><div className="letterhead-top"><img src={logo} alt="Precision Management"/><div><b>PRECISION MANAGEMENT</b><span>Lead with Passion. Serve with Precision.</span></div></div><div className="letterhead-body"><p>[Date]</p><p>[Recipient name]<br/>[Organization]<br/>[Address]</p><p>Dear [Recipient name],</p><p>This letterhead concept pairs formal correspondence with the same clear hierarchy used across owner and partner materials.</p><p>Sincerely,<br/>Precision Management</p></div></div><Footer/></section></>; }
function WebsiteConcept() { return <><section className="pdf-page"><Header label="Website/UI concept"/><div className="browser"><div className="browser-bar"><i/><i/><i/></div><div className="website-hero"><img src={photo} alt="Precision Management property"/><div><img src={logo} alt="Precision Management"/><p className="kicker">Professional property management</p><h1>Lead with Passion.<br/>Serve with Precision.</h1><p>Comprehensive management, from strategy to service.</p><div className="website-actions"><b>WORK WITH US</b><span>RESIDENT SUPPORT</span></div></div></div></div><Footer/></section><section className="pdf-page"><Header label="Website/UI / information architecture"/><div className="intro"><p className="kicker">Decision paths</p><h1>Make the next step obvious.</h1></div><div className="journey"><div><span>01</span><h3>Owners</h3><p>Capabilities, portfolio context, compliance confidence, assessment request.</p></div><div><span>02</span><h3>Residents</h3><p>Support channels, clear communications, service information.</p></div><div><span>03</span><h3>Partners</h3><p>Vendor requirements, registration, working relationship.</p></div></div><div className="callout"><img src={photo} alt="Precision Management property"/><div><p className="kicker">Design principle</p><h2>Let evidence carry the pitch.</h2><p>Show the actual portfolio environment, official identity, and clear service paths before introducing decorative UI.</p></div></div><Footer/></section></>; }

export function generateStaticParams() { return Object.keys(assets).map((asset) => ({ asset })); }
export const dynamicParams = false;

export default async function PrintAsset({ params }: { params: Promise<{ asset: string }> }) {
  const { asset } = await params;
  if (!(asset in assets)) notFound();
  const key = asset as Asset;
  if (key === "brand-guidelines") return <EditableDocument><Cover asset={key}/><BrandGuidelines/></EditableDocument>;
  if (key === "owner-acquisition") return <EditableDocument><OwnerSheet/></EditableDocument>;
  if (key === "resident-communication") return <EditableDocument><ResidentNotice/></EditableDocument>;
  if (key === "print-collateral") return <EditableDocument><PrintCollateral/></EditableDocument>;
  return <EditableDocument><WebsiteConcept/></EditableDocument>;
}
