export const copyDeck = {
  disclaimer: "Independent Concept — created by Ger'Quia Abner. Not commissioned by, affiliated with, or endorsed by Precision Management.",
  hero: {
    headline: "Property Marketing & Move-In Communication System™",
    subheadline: "A practical toolkit built for leasing teams, property managers, and resident-facing staff — ready to deploy across move-ins, renewals, notices, and property marketing.",
  },
  finalCTA: {
    title: "Built as Proof. Ready to Discuss.",
    subcopy: "I created this independent concept to demonstrate how I think, build, and execute marketing systems that help properties lease better, communicate better, and present better.",
    buttonText: "Contact Ger'Quia Abner",
  },
  executiveSummary: [
    ["What I researched", "Public footprint, verified scale signals, existing positioning, the leasing lifecycle, and the operational gaps between office staff, prospects, and residents."],
    ["What I identified", "A need for practical, editable assets that help priority properties present better, communicate more clearly, and move through the leasing cycle faster."],
    ["What I built", "A scalable template system covering property flyers, leasing brochures, move-in kits, renewal communications, resident notices, and business cards."],
    ["What this improves", "Leasing clarity, move-in readiness, renewal retention, resident communication consistency, and the ability to deploy professional materials at any property."],
    ["Hiring value", "Research discipline, compliance-aware copy, operational systems thinking, Fair Housing awareness, and full-stack execution in one presentation."],
  ],
  operatingSystem: [
    ["01", "Market the property", "Every available unit gets a professional flyer, a leasing brochure, and a digital post — consistent, editable, and ready in hours instead of days.", "Property flyers · leasing brochures · digital assets"],
    ["02", "Move residents in", "A complete move-in kit reduces first-week confusion, sets service expectations, and starts the resident relationship with clarity instead of friction.", "Welcome letter · checklist · utilities guide · contact card"],
    ["03", "Retain and renew", "A structured renewal communication system reaches residents at the right time with the right message — clear, professional, and non-pushy.", "Renewal letter · FAQ sheet · door notice · retention offer"],
    ["04", "Communicate operationally", "Standard notice templates keep every property communication legally safe, consistently formatted, and clearly branded across maintenance, policy, and payments.", "Maintenance notice · inspection notice · payment reminder · portal announcement"],
  ],
  toolkitExecution: [
    {
      label: "Leasing Support",
      icon: "Leasing",
      problem: "Priority properties lack professional marketing materials that match the quality of larger operators.",
      assets: ["Property flyers (1BR / 2BR / 3BR)", "Availability flyer", "Move-in special flyer", "Open house event flyer", "Leasing brochure + unit comparison"],
      use: "Leasing teams can deploy a ready-to-edit flyer for any unit in minutes — consistent across every property.",
    },
    {
      label: "Move-In Communication",
      icon: "Move-In",
      problem: "Residents arrive without enough information, creating avoidable friction in the first week.",
      assets: ["Move-in welcome letter", "Move-in checklist", "Utilities setup guide", "Maintenance request guide", "Office contact card"],
      use: "A single move-in packet sets expectations, reduces office call volume, and starts the relationship professionally.",
    },
    {
      label: "Renewal Retention",
      icon: "Renewal",
      problem: "Renewals are lost when communication is delayed, confusing, or feels threatening.",
      assets: ["Lease renewal letter", "Renewal FAQ sheet", "Door notice template", "Resident retention offer", "Renewal reminder copy"],
      use: "A structured renewal outreach sequence gives residents clear options and a respectful deadline — reducing turnover.",
    },
    {
      label: "Resident Operations",
      icon: "Email",
      problem: "Operational notices look inconsistent, lack clear next steps, and carry Fair Housing risk when written ad hoc.",
      assets: ["Maintenance notice", "Inspection notice", "Community update", "Payment reminder", "Emergency maintenance update", "Resident portal announcement"],
      use: "Fair Housing-safe notice templates every staff member can use — consistently worded, consistently branded.",
    },
  ],
  assetLibraryCategories: [
    {
      id: "property-flyers",
      number: "01",
      title: "Property Flyers",
      count: 5,
      description: "Editable, print-ready flyers for 1BR, 2BR, 3BR, available units, move-in specials, and leasing events.",
      assets: ["1-Bedroom Flyer", "2-Bedroom Flyer", "3-Bedroom Flyer", "Move-In Special Flyer", "Open House Flyer"],
      route: "/print/property-flyer",
      downloadHref: null,
    },
    {
      id: "leasing-brochures",
      number: "02",
      title: "Leasing Brochures",
      count: 4,
      description: "A repeatable leasing packet covering property overview, unit comparison, amenities, and application process.",
      assets: ["Property Overview", "Unit Comparison Sheet", "Amenities Sheet", "Application Process Sheet"],
      route: "/print/leasing-brochure",
      downloadHref: null,
    },
    {
      id: "floor-plans",
      number: "03",
      title: "Floor Plans",
      count: 1,
      description: "Professional property sheet highlighting specific floor plans, square footage, amenities, and pricing.",
      assets: ["Floor Plan Property Sheet"],
      route: "/print/floor-plan",
      downloadHref: null,
    },
    {
      id: "move-in-templates",
      number: "04",
      title: "Move-In Kit",
      count: 5,
      description: "The complete move-in communication kit — from welcome letter through first-week contact card.",
      assets: ["Welcome Letter", "Move-In Checklist", "Utilities Setup Guide", "Maintenance Request Guide", "Office Contact Card"],
      route: "/print/move-in-kit",
      downloadHref: null,
    },
    {
      id: "renewal-templates",
      number: "05",
      title: "Lease Renewals",
      count: 4,
      description: "A structured renewal communication system — letter, FAQ, door notice, and retention offer.",
      assets: ["Renewal Letter", "FAQ Sheet", "Door Notice", "Retention Offer"],
      route: "/print/lease-renewal",
      downloadHref: null,
    },
    {
      id: "resident-notices",
      number: "06",
      title: "Resident Notices",
      count: 6,
      description: "Fair Housing-safe operational notice templates for maintenance, inspections, payments, and community updates.",
      assets: ["Maintenance Notice", "Inspection Notice", "Community Update", "Payment Reminder", "Emergency Update", "Portal Announcement"],
      route: "/print/resident-notices",
      downloadHref: null,
    },
    {
      id: "business-cards",
      number: "07",
      title: "Business Cards",
      count: 6,
      description: "Corporate and property-level cards for managers, leasing specialists, maintenance staff, and QR contact cards.",
      assets: ["Corporate Card", "Property Manager Card", "Leasing Specialist Card", "Maintenance Card", "Resident Support Card", "QR Contact Card"],
      route: "/print/business-cards",
      downloadHref: null,
    },
    {
      id: "staff-operations",
      number: "08",
      title: "Staff & Operations",
      count: 2,
      description: "Internal templates for property teams, including timesheets and bonus/compensation notices.",
      assets: ["Staff Timesheet", "Bonus / Compensation Notice"],
      route: "/print/staff-operations",
      downloadHref: null,
    },
  ],
  deliveryPackage: [
    "Property Flyer Templates (5)",
    "Leasing Brochure Packet (4 pages)",
    "Floor Plan Sheets (1)",
    "Move-In Kit (5 templates)",
    "Renewal Communication (4 templates)",
    "Resident Notices (6 templates)",
    "Business Card System (6 variants)",
    "Staff & Operations (2 templates)",
  ],
};
